name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
        docker login --username JeremiePlam --password ${{ secrets.GH_PAT }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/JeremiePlam/plexamp-musiccleaner:$(date +%s)
        docker push ghcr.io/JeremiePlam/plexamp-musiccleaner:$(date +%s)
